# Generated by Django 4.2.1 on 2023-11-24 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_item_item_food"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="item_food",
            new_name="item_img",
        ),
    ]
