# Generated by Django 4.2.4 on 2023-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_moviedata_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="img",
            field=models.ImageField(
                default="Images/None/Noimg.jpg", upload_to="Images/"
            ),
        ),
        migrations.AlterField(
            model_name="moviedata",
            name="typ",
            field=models.CharField(default="Action", max_length=20),
        ),
    ]
