# Generated by Django 4.2.4 on 2023-11-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profilepic.jpg", upload_to="profile_images"
            ),
        ),
    ]
