# Generated by Django 4.2.4 on 2023-11-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(upload_to="profile_images"),
        ),
    ]
